version: '3.7'
services:

    mysql:
        container_name: mysql
        image: 'mysql:8.0.16'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - "3306:3306"
        expose:
          - "22"  
        environment:
          - MYSQL_ROOT_PASSWORD=rootpass
          - MYSQL_USER=local
          - MYSQL_PASSWORD=local
          - MYSQL_DATABASE=local
